// Generated by Reflector from C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.Entity\v4.0_4.0.0.0__b77a5c561934e089\System.Data.Entity.dll
using System;
using System.Linq.Expressions;

namespace Epic.Data.Objects
{
  
  internal static class Error
  {
    internal static Exception UnhandledBindingType(MemberBindingType memberBindingType)
    {

        // EntityUtil.NotSupported(System.Data.Entity.Strings.ELinq_UnhandledBindingType(memberBindingType));

        return EntityUtil.NotSupported(memberBindingType.ToString());
    }
    
    internal static Exception UnhandledExpressionType(ExpressionType expressionType)
    {
        // EntityUtil.NotSupported(System.Data.Entity.Strings.ELinq_UnhandledExpressionType(expressionType));
        return EntityUtil.NotSupported(expressionType.ToString());
    }
  }
}
